import jsPDF from "jspdf"

export function generatePrescriptionPDF({
  clinicName,
  doctorName,
  patientPhone,
  medicines,
  notes
}) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(18)
  doc.text(clinicName, 20, 20)

  doc.setFontSize(11)
  doc.text("Your clinic, now digital", 20, 28)

  doc.line(20, 32, 190, 32)

  // Meta
  doc.setFontSize(12)
  doc.text(`Doctor: ${doctorName}`, 20, 42)
  doc.text(`Patient: ${patientPhone}`, 20, 50)
  doc.text(
    `Date: ${new Date().toLocaleDateString()}`,
    20,
    58
  )

  // Medicines
  let y = 72
  doc.setFontSize(13)
  doc.text("Prescription", 20, y)

  y += 10
  doc.setFontSize(11)

  medicines.forEach((m, i) => {
    doc.text(
      `${i + 1}. ${m.name} — ${m.dosage} — ${m.timing}`,
      20,
      y
    )
    y += 8
  })

  // Notes
  if (notes) {
    y += 8
    doc.text("Notes:", 20, y)
    y += 6
    doc.text(notes, 20, y)
  }

  // Footer
  doc.setFontSize(10)
  doc.text(
    "Generated by Devmurari Care",
    20,
    285
  )

  doc.save(`Prescription-${patientPhone}.pdf`)
}